apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: devtools
  name: devtools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devtools
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: devtools
    spec:
      containers:
      - image: registry.digitalocean.com/dwt-development/devtools
        name: devtools
        resources: {}
      imagePullSecrets:
        - name: registry-dwt-development
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: devtools
  name: devtools
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: devtools
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: devtools
  annotations:
    external-dns.alpha.kubernetes.io/hostname: online-dev-tools.com
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
    - hosts:
        - online-dev-tools.com
      secretName: devtools
  rules:
    - host: online-dev-tools.com
      http:
        paths:
          - path: /
            backend:
              serviceName: devtools
              servicePort: 80
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: testdevtools
  annotations:
    external-dns.alpha.kubernetes.io/hostname: test.online-dev-tools.com
    kubernetes.io/ingress.class: "nginx"
    external-dns.alpha.kubernetes.io/ttl: "120" #optional
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
       - test.online-dev-tools.com
      secretName: nginx-tls
  rules:
    - host: test.online-dev-tools.com
      http:
        paths:
          - path: /
            backend:
              serviceName: devtools
              servicePort: 80